# -*- coding: utf-8 -*-
"""TitanicSurvivalAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MiBQf6w0jAKSpK4Vf0kiUFY47k_O2ZOc
"""

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("Titanic-Dataset-selected-columns.csv")

# Display first 5 rows
print("First 5 Rows:")
print(df.head())

# Dataset information
print("\nDataset Info:")
print(df.info())

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Handle missing Age values
df['Age'] = df['Age'].fillna(df['Age'].median())

# -----------------------------
# 1. Who survived more: Males or Females?
# -----------------------------
print("\nSurvival Rate by Gender:")
print(df.groupby('Sex')['Survived'].mean())

plt.figure(figsize=(6,4))
sns.barplot(x='Sex', y='Survived', data=df)
plt.title('Survival Rate by Gender')
plt.ylabel('Survival Rate')
plt.show()

# -----------------------------
# 2. Did Passenger Class Affect Survival?
# -----------------------------
print("\nSurvival Rate by Passenger Class:")
print(df.groupby('Pclass')['Survived'].mean())

plt.figure(figsize=(6,4))
sns.barplot(x='Pclass', y='Survived', data=df)
plt.title('Survival Rate by Passenger Class')
plt.ylabel('Survival Rate')
plt.show()

# -----------------------------
# 3. Survival Rate by Age Group
# -----------------------------
bins = [0, 12, 18, 35, 60, 100]
labels = ['Child', 'Teen', 'Young Adult', 'Adult', 'Senior']

df['Age_Group'] = pd.cut(df['Age'], bins=bins, labels=labels)

print("\nSurvival Rate by Age Group:")
print(df.groupby('Age_Group')['Survived'].mean())

plt.figure(figsize=(8,4))
sns.barplot(x='Age_Group', y='Survived', data=df)
plt.title('Survival Rate by Age Group')
plt.ylabel('Survival Rate')
plt.show()

# -----------------------------
# 4. Histogram of Passenger Ages
# -----------------------------
plt.figure(figsize=(8,4))
sns.histplot(df['Age'], bins=20, kde=True)
plt.title('Distribution of Passenger Ages')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

# -----------------------------
# Summary Statistics
# -----------------------------
print("\nDataset Summary:")
print(df.describe())